### ISSUE TITLE
Trying to understand how to generate a java sdk locally with a specific package name and the correct directory structure

### ISSUE THREAD

**Issue by bhurley-sayari** [fern-api/fern-java#357]
Hi I'm trying to use this to generate an sdk in java, but running into some issues with the generated package name and directory structure when performing local generation.

The relevant bits of my generator.yaml
```
      - name: fernapi/fern-java-sdk
        version: 0.5.10
        output:
          location: local-file-system
          path: ../generated/java
        config:
          packagePrefix: com.sayari.sdk
          mode: client
```

What I would expect to happen here is

1. The java files would be output to `./generated/java/src/main/java/com/sayari/sdk`
2. The java files would contain an appropriate package declaration.  e.g. `package com.sayari.sdk.core;` etc.
3. The import statements would respect the generated package names, e.g. ` import com.sayari.sdk.resources.auth.AuthClient;`

But none of the above seems to be taking place.  It looks to me that [this class](https://github.com/fern-api/fern-java/blob/4718c24fe038881e2f20421daffad041be9977c8/generator-utils/src/main/java/com/fern/java/output/AbstractGeneratedJavaFile.java#L49) is blowing out the packagePrefix when performing local generation?  Or is the expectation that when performing local generation that I will fix these things up after the code generation takes place?
