### ISSUE TITLE
[Bug] SDK always tries to serialize request body even when it is optional.empty()

### ISSUE THREAD

**Issue by dsinghvi** [fern-api/fern-java#369]
**Describe the bug**
The SDK always tries to serialize a request body parameter even if the parameter is `Optional.empty()`. 

**To Reproduce**
```yaml
services: 
  endpoints: 
    doThing: 
       request: 
          name: MyRequest
          query-parameters: 
             boo: optional<string>
          body: optional<map<string, string>>
```

**Expected behavior**
Instead of this
```java
var body = RequestBody.create(
         ObjectMappers.JSON_MAPPER.writeValueAsBytes(request.getBody()), APPLICATION_JSON_MEDIA);
```
something like this should be gnerated
```java
var body = RequestBody.create("", null)
if (request.body.isPresent()) {
  body = RequestBody.create(
         ObjectMappers.JSON_MAPPER.writeValueAsBytes(request.getBody().get()), APPLICATION_JSON_MEDIA);
}
```
